import sys
import time

import pandas as pd

IN = "PRs/Full_data"
OUT_JSONL = "cleaned_prs.jsonl"
OUT_CSV = "cleaned_prs.csv"
LOG = "clean.log"

START = "2021-09-20"  # study window by the date the PR was created
END = "2026-09-20"

# Temporary rec from AI since I discussed temp solutions until RABBIT-ng can be set up
BOT_LOGINS = {"zephyrbot"}  # also counted as bot GitHub type "Bot" and names ending in [bot]

FEEDBACK = ["comments", "reviews", "review_comments"]  # what people write on a PR
EVENTS = FEEDBACK + ["commits"]

# Helpful for me for logging and the overleaf numbers stuff
# This part was copied from the mining file mainly
def log(msg):
    line = f"{time.strftime('%H:%M:%S')} {msg}"
    print(line, flush=True)
    with open(LOG, "a") as f:
        f.write(line + "\n")

# Todo here is check if its bot and GitHub type bot [bot] or something like that
# check this again later on comeback to this
def is_bot(login, kind=None):
    return kind == "Bot" or login in BOT_LOGINS or str(login).endswith("[bot]")

# if comment or review or commit was written by the PR author or not
# differentiates between self comments and other actual feedback comments from tem members
def by_author(event, author):
    return isinstance(author, str) and event["author"] == author


def by_person(event, author):
    #Written by a real person who is not the PR author
    return not by_author(event, author) and not is_bot(event["author"], event.get("type"))


def got_any_feedback(row):
    return any(not by_author(e, row["author"]) for col in FEEDBACK for e in row[col])


def got_person_feedback(row):
    return any(by_person(e, row["author"]) for col in FEEDBACK for e in row[col])


def first_response(row):
    # Time of the first feedback from a real person ("9999" if nobody responded)
    times = [e["at"] for col in FEEDBACK for e in row[col] if by_person(e, row["author"]) and e["at"]]
    return min(times) if times else "9999"

# THis was generated by AI here which helped me remove authors own messages that were sent before a review 
# or feedback was made yet
def drop_self_notes(events, author, first):
    """Remove the author's own messages written before anyone else responded."""
    return [e for e in events if not (by_author(e, author) and e["at"] and e["at"] < first)]

# logging stuff below from internet and AI
def count_items(df):
    return sum(df[col].str.len().sum() for col in EVENTS)


def show(label, before, after):
    log(f"{label:<34} removed {before - after:>6}   remaining {after}")


def main():

    #######################################################################################
    #This chunk of code is completely AI generated for the purpose of debugging the zip file issue I was running into
    # Yet to be tested still trying to think of a way to make the transition from mining to cleaning
    path = sys.argv[1] if len(sys.argv) > 1 else IN
    try:
        df = pd.read_json(path, lines=True, dtype=False, convert_dates=False)
    except ValueError:
        sys.exit(f"{path} is not the raw output of main.py (one JSON object per line). "
                 "If it was opened in Excel and saved again, use the original file.")
    log(f"read {len(df)} PRs from {path}")
    #########################################################################################


    # 1. Study window: keep PRs created between START and END
    before = len(df)
    day = df["created_at"].str[:10]
    df = df[(day >= START) & (day <= END)]
    show("1 outside study window", before, len(df))

    # 2. Duplicates: if a PR appears twice, keep the last copy
    before = len(df)
    df = df.drop_duplicates("number", keep="last")
    show("2 duplicate PRs", before, len(df))

    # 3. PRs opened by bots
    before = len(df)
    df = df[~df["author"].apply(is_bot)].copy()
    show("3 PRs created by bots", before, len(df))

    # taking note of who gave feedback now, before bot messages are removed in step 4
    df["any_feedback"] = df.apply(got_any_feedback, axis=1)
    df["person_feedback"] = df.apply(got_person_feedback, axis=1)

    # 4. Messages and commits written by bots (the PR stays)
    items = count_items(df)
    for col in EVENTS:
        df[col] = df[col].apply(lambda events: [e for e in events if not is_bot(e["author"], e.get("type"))])
    log(f"4 bot comments/reviews/commits     removed {items - count_items(df)} items, PRs unchanged")

    # 5. The author's own early messages (before anyone else responded)
    items = count_items(df)
    first = df.apply(first_response, axis=1)
    for col in FEEDBACK:
        df[col] = [drop_self_notes(events, author, f) for events, author, f in zip(df[col], df["author"], first)]
    log(f"5 author's early self-notes        removed {items - count_items(df)} items, PRs unchanged")

    # 6. PRs that never got feedback
    #    merged PRs: removed only if nobody but the author wrote anything (bots count)
    #    closed or open PRs: removed if no real person gave feedback
    # Ai helped with this one to recognize how to best handle this scenario especially since right now we dont have any bot classification filter
    merged = df["merged_at"].notna()
    is_open = df["closed_at"].isna() & ~merged
    nothing = (merged & ~df["any_feedback"]) | (~merged & ~df["person_feedback"])
    log(f"   closed without merging: {(nothing & ~merged & ~is_open).sum()}, still open: {(nothing & is_open).sum()}, "
        f"merged: {(nothing & merged).sum()}  (kept: {(merged & ~nothing & ~df['person_feedback']).sum()} merged PRs with bot feedback only)")
    before = len(df)
    df = df[~nothing]
    show("6 PRs that never got feedback", before, len(df))

    # Save: the full cleaned PRs, plus a small one-row-per-PR table
    df = df.drop(columns=["any_feedback", "person_feedback"])
    df.to_json(OUT_JSONL, orient="records", lines=True)

    flat = df.drop(columns=EVENTS)
    flat["status"] = "closed_unmerged"
    flat.loc[df["merged_at"].notna(), "status"] = "merged"
    flat.loc[df["merged_at"].isna() & df["closed_at"].isna(), "status"] = "open"
    for col in EVENTS:
        flat["n_" + col] = df[col].str.len()
    flat.to_csv(OUT_CSV, index=False)

    log(f"FINISHED - {len(df)} PRs in {OUT_JSONL} and {OUT_CSV}")


if __name__ == "__main__":
    main()
